//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 JG.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDP_OLE_INIT_FAILED             102
#define IDD_Login                       103
#define IDR_MAINFRAME                   128
#define IDR_JGTYPE                      130
#define IDI_FastTrade                   131
#define IDI_xcsc                        132
#define IDD_DIALOG1                     310
#define IDD_DIALOGQQQ                   310
#define IDB_BITMAP_CLOSE                312
#define IDB_BITMAP_CLOSE_HOVER          313
#define IDB_BITMAP_OPEN                 314
#define IDB_BITMAP4                     315
#define IDB_BITMAP_OPEN_HOVER           315
#define IDD_DIALOG_SETTING              316
#define IDD_DIALOG3                     317
#define IDD_DIALOG_Keypad               317
#define IDD_DIALOG2                     318
#define IDD_DIALOG_Edit                 318
#define IDC_User                        1000
#define IDC_Pass                        1001
#define IDC_Login                       1002
#define IDC_FontSize                    1003
#define IDC_Btn_Setting                 1004
#define IDC_EDIT_Vcode                  1005
#define ID_Cancel                       1006
#define IDC_Trade                       1010
#define IDC_Market_SSE                  1011
#define IDC_Market_SZSE                 1012
#define IDC_STATIC_User                 1013
#define IDC_STATIC_Pass                 1014
#define IDC_STATIC_Trade                1015
#define IDC_STATIC_Market               1016
#define IDC_STATIC_LoinType             1017
#define IDC_STATIC_Market2              1018
#define IDC_STATIC_Font                 1018
#define IDC_STATIC_Market3              1019
#define IDC_STATIC_FontStyle            1019
#define IDC_Market_SZSE2                1020
#define IDC_AlertServer                 1020
#define IDC_STATIC_Market4              1021
#define IDC_STATIC_Market5              1022
#define IDC_STATIC_VCode                1023
#define IDC_AlertServer_SSE             1024
#define IDC_AlertServer_SZSE            1025
#define IDC_LoginType                   1031
#define IDC_AssetProp                   1032
#define IDC_Font                        1033
#define IDC_Font_Style                  1034
#define IDC_PROGRESS_Login              1036
#define IDC_Help                        1038
#define IDC_STATIC_Trade_Address        1039
#define IDC_STATIC_Market_SSE           1040
#define IDC_STATIC_Market_SZSE          1041
#define IDC_STATIC_Alert                1042
#define IDC_COMBO_Trade_Address         1043
#define IDC_COMBO_Market_SSE            1044
#define IDC_COMBO_Market_SZSE           1045
#define IDC_COMBO_Alert                 1046
#define IDC_BUTTON_Confirm              1047
#define IDC_BUTTON_Cancel               1048
#define IDC_STATIC_Update               1049
#define IDC_COMBO_Update                1050
#define IDC_STATIC_Alert_SSE            1051
#define IDC_COMBO_Alert_SSE             1052
#define IDC_STATIC_Alert_SZSE           1053
#define IDC_BUTTON_TradeAddr_Add        1054
#define IDC_BUTTON_TradeAddr_Modify     1055
#define IDC_EDIT_Name                   1055
#define IDC_BUTTON_TradeAddr_Delete     1056
#define IDC_EDIT_Addr                   1056
#define IDC_EDIT_Port                   1057
#define IDC_COMBO_Alert_SZSE            1057
#define IDC_STATIC_Name                 1058
#define IDC_STATIC_Addr                 1059
#define IDC_STATIC_Port                 1060
#define IDC_BUTTON1                     1061
#define IDC_BUTTON_Edit_Confirm         1061
#define IDC_BUTTON_CheckVCode           1061
#define IDC_BUTTON_Edit_Cancel          1062
#define IDC_BUTTON_MarketSSE_Add        1066
#define IDC_BUTTON_MarketSSE_Modify     1067
#define IDC_BUTTON_MarketSSE_Delete     1068
#define IDC_BUTTON_MarketSZSE_Add       1069
#define IDC_BUTTON_MarketSZSE_Modify    1070
#define IDC_BUTTON_MarketSZSE_Delete    1071
#define IDC_BUTTON_Alert_Add            1072
#define IDC_BUTTON_Alert_Modify         1073
#define IDC_BUTTON_TradeAddr_Delete4    1074
#define IDC_BUTTON_Alert_Delete         1074
#define IDC_BUTTON_Update_Add           1075
#define IDC_BUTTON_Update_Modify        1076
#define IDC_BUTTON_Alert_Delete2        1077
#define IDC_BUTTON_Update_Delete        1077
#define IDC_BUTTON_Alert_Add_SSE        1078
#define IDC_BUTTON_Alert_Modify_SSE     1079
#define IDC_BUTTON_Alert_Delete_SSE     1080
#define IDC_BUTTON_Alert_Add_SZSE       1081
#define IDC_BUTTON_Alert_Modify_SZSE    1082
#define IDC_BUTTON_Alert_Delete_SZSE    1083
#define IDB_PNG_DOCKCENTER              1096
#define IDB_PNG_DOCKDOWN                1097
#define IDB_PNG_DOCKLEFT                1098
#define IDB_PNG_DOCKRIGHT               1099
#define IDB_PNG_DOCKUP                  1100
#define IDC_STATIC_Version              1101
#define IDC_Pad_Button1                 1102
#define IDC_Pad_Button2                 1103
#define IDC_Pad_Button3                 1104
#define IDC_Pad_Button4                 1105
#define IDC_Pad_Button5                 1106
#define IDC_Pad_Button6                 1107
#define IDC_Pad_Button7                 1108
#define IDC_Pad_Button8                 1109
#define IDC_Pad_Button9                 1110
#define IDC_Pad_Button10                1111
#define IDC_Pad_Button_Delete           1112
#define IDC_Pad_Button_Confirm          1113
#define IDC_EDIT_NO                     1114
#define IDC_EDIT_NOUSE                  1114
#define IDC_Pad_Button_Confirm2         1117
#define IDC_Pad_Button_Clear            1117

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        320
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
